#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication snappyHexMesh -overwrite
cp 0/alpha.water.org 0/alpha.water
runApplication setFields
runApplication `getApplication`

# ----------------------------------------------------------------- end-of-file
